<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Metrics.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/Metrics.php';
}

namespace IceMX
{
    global $IceMX__t_SessionMetrics;
    class SessionMetrics extends \IceMX\Metrics
    {
        public function __construct($id='', $total=0, $current=0, $totalLifetime=0, $failures=0, $forwardedClient=0, $forwardedServer=0, $routingTableSize=0, $queuedClient=0, $queuedServer=0, $overriddenClient=0, $overriddenServer=0)
        {
            parent::__construct($id, $total, $current, $totalLifetime, $failures);
            $this->forwardedClient = $forwardedClient;
            $this->forwardedServer = $forwardedServer;
            $this->routingTableSize = $routingTableSize;
            $this->queuedClient = $queuedClient;
            $this->queuedServer = $queuedServer;
            $this->overriddenClient = $overriddenClient;
            $this->overriddenServer = $overriddenServer;
        }

        public function ice_id()
        {
            return '::IceMX::SessionMetrics';
        }

        public static function ice_staticId()
        {
            return '::IceMX::SessionMetrics';
        }

        public function __toString()
        {
            global $IceMX__t_SessionMetrics;
            return IcePHP_stringify($this, $IceMX__t_SessionMetrics);
        }

        public $forwardedClient;
        public $forwardedServer;
        public $routingTableSize;
        public $queuedClient;
        public $queuedServer;
        public $overriddenClient;
        public $overriddenServer;
    }

    global $IceMX__t_Metrics;
    global $IcePHP__t_int;
    $IceMX__t_SessionMetrics = IcePHP_defineClass('::IceMX::SessionMetrics', '\\IceMX\\SessionMetrics', -1, false, false, $IceMX__t_Metrics, array(
        array('forwardedClient', $IcePHP__t_int, false, 0),
        array('forwardedServer', $IcePHP__t_int, false, 0),
        array('routingTableSize', $IcePHP__t_int, false, 0),
        array('queuedClient', $IcePHP__t_int, false, 0),
        array('queuedServer', $IcePHP__t_int, false, 0),
        array('overriddenClient', $IcePHP__t_int, false, 0),
        array('overriddenServer', $IcePHP__t_int, false, 0)));
}
namespace
{new Ice\SliceChecksumInit(array(
    "::IceMX::SessionMetrics" => "221020be2c80301fb4dbb779e21b190"));
}
?>
