<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `PermissionsVerifier.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Glacier2/SSLInfo.php';
}

namespace Glacier2
{
    global $Glacier2__t_PermissionDeniedException;
    class PermissionDeniedException extends \Ice\UserException
    {
        public function __construct($reason='')
        {
            $this->reason = $reason;
        }

        public function ice_id()
        {
            return '::Glacier2::PermissionDeniedException';
        }

        public function __toString()
        {
            global $Glacier2__t_PermissionDeniedException;
            return IcePHP_stringifyException($this, $Glacier2__t_PermissionDeniedException);
        }

        public $reason;
    }
    global $IcePHP__t_string;

    $Glacier2__t_PermissionDeniedException = IcePHP_defineException('::Glacier2::PermissionDeniedException', '\\Glacier2\\PermissionDeniedException', true, null, array(
        array('reason', $IcePHP__t_string, false, 0)));
}

namespace Glacier2
{
    global $Glacier2__t_PermissionsVerifier;
    global $Glacier2__t_PermissionsVerifierPrx;

    class PermissionsVerifierPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Glacier2::PermissionsVerifier', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Glacier2::PermissionsVerifier', $facet);
        }

        public static function ice_staticId()
        {
            return '::Glacier2::PermissionsVerifier';
        }
    }
    $Glacier2__t_PermissionsVerifier = IcePHP_defineClass('::Glacier2::PermissionsVerifier', '\\Glacier2\\PermissionsVerifier', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $Glacier2__t_PermissionsVerifierPrx = IcePHP_defineProxy('::Glacier2::PermissionsVerifier', $Ice__t_ObjectPrx, null);

    global $IcePHP__t_string;
    global $IcePHP__t_bool;
    IcePHP_defineOperation($Glacier2__t_PermissionsVerifierPrx, 'checkPermissions', 2, 1, 2, array(array($IcePHP__t_string), array($IcePHP__t_string)), array(array($IcePHP__t_string)), array($IcePHP__t_bool), array($Glacier2__t_PermissionDeniedException));
}

namespace Glacier2
{
    global $Glacier2__t_SSLPermissionsVerifier;
    global $Glacier2__t_SSLPermissionsVerifierPrx;

    class SSLPermissionsVerifierPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Glacier2::SSLPermissionsVerifier', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Glacier2::SSLPermissionsVerifier', $facet);
        }

        public static function ice_staticId()
        {
            return '::Glacier2::SSLPermissionsVerifier';
        }
    }
    $Glacier2__t_SSLPermissionsVerifier = IcePHP_defineClass('::Glacier2::SSLPermissionsVerifier', '\\Glacier2\\SSLPermissionsVerifier', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $Glacier2__t_SSLPermissionsVerifierPrx = IcePHP_defineProxy('::Glacier2::SSLPermissionsVerifier', $Ice__t_ObjectPrx, null);

    global $Glacier2__t_SSLInfo;
    global $IcePHP__t_string;
    global $IcePHP__t_bool;
    IcePHP_defineOperation($Glacier2__t_SSLPermissionsVerifierPrx, 'authorize', 2, 1, 2, array(array($Glacier2__t_SSLInfo)), array(array($IcePHP__t_string)), array($IcePHP__t_bool), array($Glacier2__t_PermissionDeniedException));
}
namespace
{new Ice\SliceChecksumInit(array(
    "::Glacier2::PermissionDeniedException" => "27def8d4569ab203b629b9162d530ba",
    "::Glacier2::PermissionsVerifier" => "fcf33ee75c6e0e651d33c88bbca148d",
    "::Glacier2::SSLPermissionsVerifier" => "c9d5a5d4c26aae9cb2da81d56f9f9e1"));
}
?>
