<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `RouterF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Glacier2
{
    global $Glacier2__t_Router;
    global $Glacier2__t_RouterPrx;
    if(!isset($Glacier2__t_Router))
    {
        $Glacier2__t_Router = IcePHP_declareClass('::Glacier2::Router');
        $Glacier2__t_RouterPrx = IcePHP_declareProxy('::Glacier2::Router');
    }
}
?>
