<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `SSLInfo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/BuiltinSequences.php';
}

namespace Glacier2
{
    global $Glacier2__t_SSLInfo;
    class SSLInfo
    {
        public function __construct($remoteHost='', $remotePort=0, $localHost='', $localPort=0, $cipher='', $certs=null)
        {
            $this->remoteHost = $remoteHost;
            $this->remotePort = $remotePort;
            $this->localHost = $localHost;
            $this->localPort = $localPort;
            $this->cipher = $cipher;
            $this->certs = $certs;
        }

        public function __toString()
        {
            global $Glacier2__t_SSLInfo;
            return IcePHP_stringify($this, $Glacier2__t_SSLInfo);
        }

        public $remoteHost;
        public $remotePort;
        public $localHost;
        public $localPort;
        public $cipher;
        public $certs;
    }

    global $IcePHP__t_string;
    global $IcePHP__t_int;
    global $Ice__t_StringSeq;
    $Glacier2__t_SSLInfo = IcePHP_defineStruct('::Glacier2::SSLInfo', '\\Glacier2\\SSLInfo', array(
        array('remoteHost', $IcePHP__t_string),
        array('remotePort', $IcePHP__t_int),
        array('localHost', $IcePHP__t_string),
        array('localPort', $IcePHP__t_int),
        array('cipher', $IcePHP__t_string),
        array('certs', $Ice__t_StringSeq)));
}
namespace
{new Ice\SliceChecksumInit(array(
    "::Glacier2::SSLInfo" => "ca63bc6d361a48471c4d16ea29818e5"));
}
?>
