<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Admin.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/Identity.php';
    require_once 'Ice/BuiltinSequences.php';
    require_once 'Ice/Properties.php';
    require_once 'Ice/SliceChecksumDict.php';
    require_once 'Glacier2/Session.php';
    require_once 'IceGrid/Exception.php';
    require_once 'IceGrid/Descriptor.php';
}

namespace IceGrid
{
    global $IceGrid__t_ServerState;
    class ServerState
    {
        const Inactive = 0;
        const Activating = 1;
        const ActivationTimedOut = 2;
        const Active = 3;
        const Deactivating = 4;
        const Destroying = 5;
        const Destroyed = 6;
    }

    $IceGrid__t_ServerState = IcePHP_defineEnum('::IceGrid::ServerState', array('Inactive', 0, 'Activating', 1, 'ActivationTimedOut', 2, 'Active', 3, 'Deactivating', 4, 'Destroying', 5, 'Destroyed', 6));
}

namespace IceGrid
{
    global $IceGrid__t_StringObjectProxyDict;

    if(!isset($IceGrid__t_StringObjectProxyDict))
    {
        global $IcePHP__t_string;
        global $Ice__t_ObjectPrx;
        $IceGrid__t_StringObjectProxyDict = IcePHP_defineDictionary('::IceGrid::StringObjectProxyDict', $IcePHP__t_string, $Ice__t_ObjectPrx);
    }
}

namespace IceGrid
{
    global $IceGrid__t_ObjectInfo;
    class ObjectInfo
    {
        public function __construct($proxy=null, $type='')
        {
            $this->proxy = $proxy;
            $this->type = $type;
        }

        public function __toString()
        {
            global $IceGrid__t_ObjectInfo;
            return IcePHP_stringify($this, $IceGrid__t_ObjectInfo);
        }

        public $proxy;
        public $type;
    }

    global $Ice__t_ObjectPrx;
    global $IcePHP__t_string;
    $IceGrid__t_ObjectInfo = IcePHP_defineStruct('::IceGrid::ObjectInfo', '\\IceGrid\\ObjectInfo', array(
        array('proxy', $Ice__t_ObjectPrx),
        array('type', $IcePHP__t_string)));
}

namespace IceGrid
{
    global $IceGrid__t_ObjectInfoSeq;

    if(!isset($IceGrid__t_ObjectInfoSeq))
    {
        global $IceGrid__t_ObjectInfo;
        $IceGrid__t_ObjectInfoSeq = IcePHP_defineSequence('::IceGrid::ObjectInfoSeq', $IceGrid__t_ObjectInfo);
    }
}

namespace IceGrid
{
    global $IceGrid__t_AdapterInfo;
    class AdapterInfo
    {
        public function __construct($id='', $proxy=null, $replicaGroupId='')
        {
            $this->id = $id;
            $this->proxy = $proxy;
            $this->replicaGroupId = $replicaGroupId;
        }

        public function __toString()
        {
            global $IceGrid__t_AdapterInfo;
            return IcePHP_stringify($this, $IceGrid__t_AdapterInfo);
        }

        public $id;
        public $proxy;
        public $replicaGroupId;
    }

    global $IcePHP__t_string;
    global $Ice__t_ObjectPrx;
    $IceGrid__t_AdapterInfo = IcePHP_defineStruct('::IceGrid::AdapterInfo', '\\IceGrid\\AdapterInfo', array(
        array('id', $IcePHP__t_string),
        array('proxy', $Ice__t_ObjectPrx),
        array('replicaGroupId', $IcePHP__t_string)));
}

namespace IceGrid
{
    global $IceGrid__t_AdapterInfoSeq;

    if(!isset($IceGrid__t_AdapterInfoSeq))
    {
        global $IceGrid__t_AdapterInfo;
        $IceGrid__t_AdapterInfoSeq = IcePHP_defineSequence('::IceGrid::AdapterInfoSeq', $IceGrid__t_AdapterInfo);
    }
}

namespace IceGrid
{
    global $IceGrid__t_ServerInfo;
    class ServerInfo
    {
        public function __construct($application='', $uuid='', $revision=0, $node='', $descriptor=null, $sessionId='')
        {
            $this->application = $application;
            $this->uuid = $uuid;
            $this->revision = $revision;
            $this->node = $node;
            $this->descriptor = $descriptor;
            $this->sessionId = $sessionId;
        }

        public function __toString()
        {
            global $IceGrid__t_ServerInfo;
            return IcePHP_stringify($this, $IceGrid__t_ServerInfo);
        }

        public $application;
        public $uuid;
        public $revision;
        public $node;
        public $descriptor;
        public $sessionId;
    }

    global $IcePHP__t_string;
    global $IcePHP__t_int;
    global $IceGrid__t_ServerDescriptor;
    $IceGrid__t_ServerInfo = IcePHP_defineStruct('::IceGrid::ServerInfo', '\\IceGrid\\ServerInfo', array(
        array('application', $IcePHP__t_string),
        array('uuid', $IcePHP__t_string),
        array('revision', $IcePHP__t_int),
        array('node', $IcePHP__t_string),
        array('descriptor', $IceGrid__t_ServerDescriptor),
        array('sessionId', $IcePHP__t_string)));
}

namespace IceGrid
{
    global $IceGrid__t_NodeInfo;
    class NodeInfo
    {
        public function __construct($name='', $os='', $hostname='', $release='', $version='', $machine='', $nProcessors=0, $dataDir='')
        {
            $this->name = $name;
            $this->os = $os;
            $this->hostname = $hostname;
            $this->release = $release;
            $this->version = $version;
            $this->machine = $machine;
            $this->nProcessors = $nProcessors;
            $this->dataDir = $dataDir;
        }

        public function __toString()
        {
            global $IceGrid__t_NodeInfo;
            return IcePHP_stringify($this, $IceGrid__t_NodeInfo);
        }

        public $name;
        public $os;
        public $hostname;
        public $release;
        public $version;
        public $machine;
        public $nProcessors;
        public $dataDir;
    }

    global $IcePHP__t_string;
    global $IcePHP__t_int;
    $IceGrid__t_NodeInfo = IcePHP_defineStruct('::IceGrid::NodeInfo', '\\IceGrid\\NodeInfo', array(
        array('name', $IcePHP__t_string),
        array('os', $IcePHP__t_string),
        array('hostname', $IcePHP__t_string),
        array('release', $IcePHP__t_string),
        array('version', $IcePHP__t_string),
        array('machine', $IcePHP__t_string),
        array('nProcessors', $IcePHP__t_int),
        array('dataDir', $IcePHP__t_string)));
}

namespace IceGrid
{
    global $IceGrid__t_RegistryInfo;
    class RegistryInfo
    {
        public function __construct($name='', $hostname='')
        {
            $this->name = $name;
            $this->hostname = $hostname;
        }

        public function __toString()
        {
            global $IceGrid__t_RegistryInfo;
            return IcePHP_stringify($this, $IceGrid__t_RegistryInfo);
        }

        public $name;
        public $hostname;
    }

    global $IcePHP__t_string;
    $IceGrid__t_RegistryInfo = IcePHP_defineStruct('::IceGrid::RegistryInfo', '\\IceGrid\\RegistryInfo', array(
        array('name', $IcePHP__t_string),
        array('hostname', $IcePHP__t_string)));
}

namespace IceGrid
{
    global $IceGrid__t_RegistryInfoSeq;

    if(!isset($IceGrid__t_RegistryInfoSeq))
    {
        global $IceGrid__t_RegistryInfo;
        $IceGrid__t_RegistryInfoSeq = IcePHP_defineSequence('::IceGrid::RegistryInfoSeq', $IceGrid__t_RegistryInfo);
    }
}

namespace IceGrid
{
    global $IceGrid__t_LoadInfo;
    class LoadInfo
    {
        public function __construct($avg1=0.0, $avg5=0.0, $avg15=0.0)
        {
            $this->avg1 = $avg1;
            $this->avg5 = $avg5;
            $this->avg15 = $avg15;
        }

        public function __toString()
        {
            global $IceGrid__t_LoadInfo;
            return IcePHP_stringify($this, $IceGrid__t_LoadInfo);
        }

        public $avg1;
        public $avg5;
        public $avg15;
    }

    global $IcePHP__t_float;
    $IceGrid__t_LoadInfo = IcePHP_defineStruct('::IceGrid::LoadInfo', '\\IceGrid\\LoadInfo', array(
        array('avg1', $IcePHP__t_float),
        array('avg5', $IcePHP__t_float),
        array('avg15', $IcePHP__t_float)));
}

namespace IceGrid
{
    global $IceGrid__t_ApplicationInfo;
    class ApplicationInfo
    {
        public function __construct($uuid='', $createTime=0, $createUser='', $updateTime=0, $updateUser='', $revision=0, $descriptor=null)
        {
            $this->uuid = $uuid;
            $this->createTime = $createTime;
            $this->createUser = $createUser;
            $this->updateTime = $updateTime;
            $this->updateUser = $updateUser;
            $this->revision = $revision;
            $this->descriptor = is_null($descriptor) ? new \IceGrid\ApplicationDescriptor : $descriptor;
        }

        public function __toString()
        {
            global $IceGrid__t_ApplicationInfo;
            return IcePHP_stringify($this, $IceGrid__t_ApplicationInfo);
        }

        public $uuid;
        public $createTime;
        public $createUser;
        public $updateTime;
        public $updateUser;
        public $revision;
        public $descriptor;
    }

    global $IcePHP__t_string;
    global $IcePHP__t_long;
    global $IcePHP__t_int;
    global $IceGrid__t_ApplicationDescriptor;
    $IceGrid__t_ApplicationInfo = IcePHP_defineStruct('::IceGrid::ApplicationInfo', '\\IceGrid\\ApplicationInfo', array(
        array('uuid', $IcePHP__t_string),
        array('createTime', $IcePHP__t_long),
        array('createUser', $IcePHP__t_string),
        array('updateTime', $IcePHP__t_long),
        array('updateUser', $IcePHP__t_string),
        array('revision', $IcePHP__t_int),
        array('descriptor', $IceGrid__t_ApplicationDescriptor)));
}

namespace IceGrid
{
    global $IceGrid__t_ApplicationInfoSeq;

    if(!isset($IceGrid__t_ApplicationInfoSeq))
    {
        global $IceGrid__t_ApplicationInfo;
        $IceGrid__t_ApplicationInfoSeq = IcePHP_defineSequence('::IceGrid::ApplicationInfoSeq', $IceGrid__t_ApplicationInfo);
    }
}

namespace IceGrid
{
    global $IceGrid__t_ApplicationUpdateInfo;
    class ApplicationUpdateInfo
    {
        public function __construct($updateTime=0, $updateUser='', $revision=0, $descriptor=null)
        {
            $this->updateTime = $updateTime;
            $this->updateUser = $updateUser;
            $this->revision = $revision;
            $this->descriptor = is_null($descriptor) ? new \IceGrid\ApplicationUpdateDescriptor : $descriptor;
        }

        public function __toString()
        {
            global $IceGrid__t_ApplicationUpdateInfo;
            return IcePHP_stringify($this, $IceGrid__t_ApplicationUpdateInfo);
        }

        public $updateTime;
        public $updateUser;
        public $revision;
        public $descriptor;
    }

    global $IcePHP__t_long;
    global $IcePHP__t_string;
    global $IcePHP__t_int;
    global $IceGrid__t_ApplicationUpdateDescriptor;
    $IceGrid__t_ApplicationUpdateInfo = IcePHP_defineStruct('::IceGrid::ApplicationUpdateInfo', '\\IceGrid\\ApplicationUpdateInfo', array(
        array('updateTime', $IcePHP__t_long),
        array('updateUser', $IcePHP__t_string),
        array('revision', $IcePHP__t_int),
        array('descriptor', $IceGrid__t_ApplicationUpdateDescriptor)));
}

namespace IceGrid
{
    global $IceGrid__t_Admin;
    global $IceGrid__t_AdminPrx;

    class AdminPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::Admin', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::Admin', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::Admin';
        }
    }
    $IceGrid__t_Admin = IcePHP_defineClass('::IceGrid::Admin', '\\IceGrid\\Admin', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_AdminPrx = IcePHP_defineProxy('::IceGrid::Admin', $Ice__t_ObjectPrx, null);

    global $IceGrid__t_ApplicationDescriptor;
    global $IceGrid__t_ApplicationUpdateDescriptor;
    global $IcePHP__t_string;
    global $IceGrid__t_ServerInstanceDescriptor;
    global $IcePHP__t_bool;
    global $IceGrid__t_ApplicationInfo;
    global $Ice__t_StringSeq;
    global $IceGrid__t_ServerInfo;
    global $IceGrid__t_ServerState;
    global $IcePHP__t_int;
    global $Ice__t_ObjectPrx;
    global $IceGrid__t_AdapterInfoSeq;
    global $Ice__t_Identity;
    global $IceGrid__t_ObjectInfo;
    global $IceGrid__t_ObjectInfoSeq;
    global $IceGrid__t_LoadInfo;
    global $IceGrid__t_NodeInfo;
    global $IceGrid__t_RegistryInfo;
    global $Ice__t_SliceChecksumDict;
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'addApplication', 0, 0, 0, array(array($IceGrid__t_ApplicationDescriptor)), null, null, array($IceGrid__t_AccessDeniedException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'syncApplication', 0, 0, 0, array(array($IceGrid__t_ApplicationDescriptor)), null, null, array($IceGrid__t_AccessDeniedException, $IceGrid__t_DeploymentException, $IceGrid__t_ApplicationNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'updateApplication', 0, 0, 0, array(array($IceGrid__t_ApplicationUpdateDescriptor)), null, null, array($IceGrid__t_AccessDeniedException, $IceGrid__t_DeploymentException, $IceGrid__t_ApplicationNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'syncApplicationWithoutRestart', 0, 0, 0, array(array($IceGrid__t_ApplicationDescriptor)), null, null, array($IceGrid__t_AccessDeniedException, $IceGrid__t_DeploymentException, $IceGrid__t_ApplicationNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'updateApplicationWithoutRestart', 0, 0, 0, array(array($IceGrid__t_ApplicationUpdateDescriptor)), null, null, array($IceGrid__t_AccessDeniedException, $IceGrid__t_DeploymentException, $IceGrid__t_ApplicationNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'removeApplication', 0, 0, 0, array(array($IcePHP__t_string)), null, null, array($IceGrid__t_AccessDeniedException, $IceGrid__t_DeploymentException, $IceGrid__t_ApplicationNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'instantiateServer', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string), array($IceGrid__t_ServerInstanceDescriptor)), null, null, array($IceGrid__t_AccessDeniedException, $IceGrid__t_ApplicationNotExistException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'patchApplication', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_bool)), null, null, array($IceGrid__t_ApplicationNotExistException, $IceGrid__t_PatchException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getApplicationInfo', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IceGrid__t_ApplicationInfo), array($IceGrid__t_ApplicationNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getDefaultApplicationDescriptor', 2, 1, 0, null, null, array($IceGrid__t_ApplicationDescriptor), array($IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getAllApplicationNames', 2, 1, 0, null, null, array($Ice__t_StringSeq), null);
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getServerInfo', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IceGrid__t_ServerInfo), array($IceGrid__t_ServerNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getServerState', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IceGrid__t_ServerState), array($IceGrid__t_ServerNotExistException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getServerPid', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IcePHP__t_int), array($IceGrid__t_ServerNotExistException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getServerAdminCategory', 2, 2, 0, null, null, array($IcePHP__t_string), null);
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getServerAdmin', 2, 2, 0, array(array($IcePHP__t_string)), null, array($Ice__t_ObjectPrx), array($IceGrid__t_ServerNotExistException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'enableServer', 2, 2, 0, array(array($IcePHP__t_string), array($IcePHP__t_bool)), null, null, array($IceGrid__t_ServerNotExistException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'isServerEnabled', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IcePHP__t_bool), array($IceGrid__t_ServerNotExistException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'startServer', 0, 0, 0, array(array($IcePHP__t_string)), null, null, array($IceGrid__t_ServerNotExistException, $IceGrid__t_ServerStartException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'stopServer', 0, 0, 0, array(array($IcePHP__t_string)), null, null, array($IceGrid__t_ServerNotExistException, $IceGrid__t_ServerStopException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'patchServer', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_bool)), null, null, array($IceGrid__t_ServerNotExistException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException, $IceGrid__t_PatchException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'sendSignal', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string)), null, null, array($IceGrid__t_ServerNotExistException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException, $IceGrid__t_BadSignalException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getAllServerIds', 2, 1, 0, null, null, array($Ice__t_StringSeq), null);
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getAdapterInfo', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IceGrid__t_AdapterInfoSeq), array($IceGrid__t_AdapterNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'removeAdapter', 0, 0, 0, array(array($IcePHP__t_string)), null, null, array($IceGrid__t_AdapterNotExistException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getAllAdapterIds', 2, 1, 0, null, null, array($Ice__t_StringSeq), null);
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'addObject', 0, 0, 0, array(array($Ice__t_ObjectPrx)), null, null, array($IceGrid__t_ObjectExistsException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'updateObject', 0, 0, 0, array(array($Ice__t_ObjectPrx)), null, null, array($IceGrid__t_ObjectNotRegisteredException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'addObjectWithType', 0, 0, 0, array(array($Ice__t_ObjectPrx), array($IcePHP__t_string)), null, null, array($IceGrid__t_ObjectExistsException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'removeObject', 0, 0, 0, array(array($Ice__t_Identity)), null, null, array($IceGrid__t_ObjectNotRegisteredException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getObjectInfo', 2, 1, 0, array(array($Ice__t_Identity)), null, array($IceGrid__t_ObjectInfo), array($IceGrid__t_ObjectNotRegisteredException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getObjectInfosByType', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IceGrid__t_ObjectInfoSeq), null);
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getAllObjectInfos', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IceGrid__t_ObjectInfoSeq), null);
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'pingNode', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IcePHP__t_bool), array($IceGrid__t_NodeNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getNodeLoad', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IceGrid__t_LoadInfo), array($IceGrid__t_NodeNotExistException, $IceGrid__t_NodeUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getNodeInfo', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IceGrid__t_NodeInfo), array($IceGrid__t_NodeNotExistException, $IceGrid__t_NodeUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getNodeAdmin', 2, 2, 0, array(array($IcePHP__t_string)), null, array($Ice__t_ObjectPrx), array($IceGrid__t_NodeNotExistException, $IceGrid__t_NodeUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getNodeProcessorSocketCount', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IcePHP__t_int), array($IceGrid__t_NodeNotExistException, $IceGrid__t_NodeUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'shutdownNode', 0, 0, 0, array(array($IcePHP__t_string)), null, null, array($IceGrid__t_NodeNotExistException, $IceGrid__t_NodeUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getNodeHostname', 2, 1, 0, array(array($IcePHP__t_string)), null, array($IcePHP__t_string), array($IceGrid__t_NodeNotExistException, $IceGrid__t_NodeUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getAllNodeNames', 2, 1, 0, null, null, array($Ice__t_StringSeq), null);
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'pingRegistry', 2, 2, 0, array(array($IcePHP__t_string)), null, array($IcePHP__t_bool), array($IceGrid__t_RegistryNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getRegistryInfo', 2, 2, 0, array(array($IcePHP__t_string)), null, array($IceGrid__t_RegistryInfo), array($IceGrid__t_RegistryNotExistException, $IceGrid__t_RegistryUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getRegistryAdmin', 2, 2, 0, array(array($IcePHP__t_string)), null, array($Ice__t_ObjectPrx), array($IceGrid__t_RegistryNotExistException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'shutdownRegistry', 2, 2, 0, array(array($IcePHP__t_string)), null, null, array($IceGrid__t_RegistryNotExistException, $IceGrid__t_RegistryUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getAllRegistryNames', 2, 2, 0, null, null, array($Ice__t_StringSeq), null);
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'shutdown', 0, 0, 0, null, null, null, null);
    IcePHP_defineOperation($IceGrid__t_AdminPrx, 'getSliceChecksums', 2, 1, 0, null, null, array($Ice__t_SliceChecksumDict), null);
}

namespace IceGrid
{
    global $IceGrid__t_FileIterator;
    global $IceGrid__t_FileIteratorPrx;

    class FileIteratorPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::FileIterator', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::FileIterator', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::FileIterator';
        }
    }
    $IceGrid__t_FileIterator = IcePHP_defineClass('::IceGrid::FileIterator', '\\IceGrid\\FileIterator', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_FileIteratorPrx = IcePHP_defineProxy('::IceGrid::FileIterator', $Ice__t_ObjectPrx, null);

    global $IcePHP__t_int;
    global $Ice__t_StringSeq;
    global $IcePHP__t_bool;
    IcePHP_defineOperation($IceGrid__t_FileIteratorPrx, 'read', 0, 0, 0, array(array($IcePHP__t_int)), array(array($Ice__t_StringSeq)), array($IcePHP__t_bool), array($IceGrid__t_FileNotAvailableException));
    IcePHP_defineOperation($IceGrid__t_FileIteratorPrx, 'destroy', 0, 0, 0, null, null, null, null);
}

namespace IceGrid
{
    global $IceGrid__t_ServerDynamicInfo;
    class ServerDynamicInfo
    {
        public function __construct($id='', $state=\IceGrid\ServerState::Inactive, $pid=0, $enabled=false)
        {
            $this->id = $id;
            $this->state = $state;
            $this->pid = $pid;
            $this->enabled = $enabled;
        }

        public function __toString()
        {
            global $IceGrid__t_ServerDynamicInfo;
            return IcePHP_stringify($this, $IceGrid__t_ServerDynamicInfo);
        }

        public $id;
        public $state;
        public $pid;
        public $enabled;
    }

    global $IcePHP__t_string;
    global $IceGrid__t_ServerState;
    global $IcePHP__t_int;
    global $IcePHP__t_bool;
    $IceGrid__t_ServerDynamicInfo = IcePHP_defineStruct('::IceGrid::ServerDynamicInfo', '\\IceGrid\\ServerDynamicInfo', array(
        array('id', $IcePHP__t_string),
        array('state', $IceGrid__t_ServerState),
        array('pid', $IcePHP__t_int),
        array('enabled', $IcePHP__t_bool)));
}

namespace IceGrid
{
    global $IceGrid__t_ServerDynamicInfoSeq;

    if(!isset($IceGrid__t_ServerDynamicInfoSeq))
    {
        global $IceGrid__t_ServerDynamicInfo;
        $IceGrid__t_ServerDynamicInfoSeq = IcePHP_defineSequence('::IceGrid::ServerDynamicInfoSeq', $IceGrid__t_ServerDynamicInfo);
    }
}

namespace IceGrid
{
    global $IceGrid__t_AdapterDynamicInfo;
    class AdapterDynamicInfo
    {
        public function __construct($id='', $proxy=null)
        {
            $this->id = $id;
            $this->proxy = $proxy;
        }

        public function __toString()
        {
            global $IceGrid__t_AdapterDynamicInfo;
            return IcePHP_stringify($this, $IceGrid__t_AdapterDynamicInfo);
        }

        public $id;
        public $proxy;
    }

    global $IcePHP__t_string;
    global $Ice__t_ObjectPrx;
    $IceGrid__t_AdapterDynamicInfo = IcePHP_defineStruct('::IceGrid::AdapterDynamicInfo', '\\IceGrid\\AdapterDynamicInfo', array(
        array('id', $IcePHP__t_string),
        array('proxy', $Ice__t_ObjectPrx)));
}

namespace IceGrid
{
    global $IceGrid__t_AdapterDynamicInfoSeq;

    if(!isset($IceGrid__t_AdapterDynamicInfoSeq))
    {
        global $IceGrid__t_AdapterDynamicInfo;
        $IceGrid__t_AdapterDynamicInfoSeq = IcePHP_defineSequence('::IceGrid::AdapterDynamicInfoSeq', $IceGrid__t_AdapterDynamicInfo);
    }
}

namespace IceGrid
{
    global $IceGrid__t_NodeDynamicInfo;
    class NodeDynamicInfo
    {
        public function __construct($info=null, $servers=null, $adapters=null)
        {
            $this->info = is_null($info) ? new \IceGrid\NodeInfo : $info;
            $this->servers = $servers;
            $this->adapters = $adapters;
        }

        public function __toString()
        {
            global $IceGrid__t_NodeDynamicInfo;
            return IcePHP_stringify($this, $IceGrid__t_NodeDynamicInfo);
        }

        public $info;
        public $servers;
        public $adapters;
    }

    global $IceGrid__t_NodeInfo;
    global $IceGrid__t_ServerDynamicInfoSeq;
    global $IceGrid__t_AdapterDynamicInfoSeq;
    $IceGrid__t_NodeDynamicInfo = IcePHP_defineStruct('::IceGrid::NodeDynamicInfo', '\\IceGrid\\NodeDynamicInfo', array(
        array('info', $IceGrid__t_NodeInfo),
        array('servers', $IceGrid__t_ServerDynamicInfoSeq),
        array('adapters', $IceGrid__t_AdapterDynamicInfoSeq)));
}

namespace IceGrid
{
    global $IceGrid__t_RegistryObserver;
    global $IceGrid__t_RegistryObserverPrx;

    class RegistryObserverPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::RegistryObserver', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::RegistryObserver', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::RegistryObserver';
        }
    }
    $IceGrid__t_RegistryObserver = IcePHP_defineClass('::IceGrid::RegistryObserver', '\\IceGrid\\RegistryObserver', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_RegistryObserverPrx = IcePHP_defineProxy('::IceGrid::RegistryObserver', $Ice__t_ObjectPrx, null);

    global $IceGrid__t_RegistryInfoSeq;
    global $IceGrid__t_RegistryInfo;
    global $IcePHP__t_string;
    IcePHP_defineOperation($IceGrid__t_RegistryObserverPrx, 'registryInit', 0, 0, 0, array(array($IceGrid__t_RegistryInfoSeq)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_RegistryObserverPrx, 'registryUp', 0, 0, 0, array(array($IceGrid__t_RegistryInfo)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_RegistryObserverPrx, 'registryDown', 0, 0, 0, array(array($IcePHP__t_string)), null, null, null);
}

namespace IceGrid
{
    global $IceGrid__t_NodeDynamicInfoSeq;

    if(!isset($IceGrid__t_NodeDynamicInfoSeq))
    {
        global $IceGrid__t_NodeDynamicInfo;
        $IceGrid__t_NodeDynamicInfoSeq = IcePHP_defineSequence('::IceGrid::NodeDynamicInfoSeq', $IceGrid__t_NodeDynamicInfo);
    }
}

namespace IceGrid
{
    global $IceGrid__t_NodeObserver;
    global $IceGrid__t_NodeObserverPrx;

    class NodeObserverPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::NodeObserver', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::NodeObserver', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::NodeObserver';
        }
    }
    $IceGrid__t_NodeObserver = IcePHP_defineClass('::IceGrid::NodeObserver', '\\IceGrid\\NodeObserver', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_NodeObserverPrx = IcePHP_defineProxy('::IceGrid::NodeObserver', $Ice__t_ObjectPrx, null);

    global $IceGrid__t_NodeDynamicInfoSeq;
    global $IceGrid__t_NodeDynamicInfo;
    global $IcePHP__t_string;
    global $IceGrid__t_ServerDynamicInfo;
    global $IceGrid__t_AdapterDynamicInfo;
    IcePHP_defineOperation($IceGrid__t_NodeObserverPrx, 'nodeInit', 0, 0, 0, array(array($IceGrid__t_NodeDynamicInfoSeq)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_NodeObserverPrx, 'nodeUp', 0, 0, 0, array(array($IceGrid__t_NodeDynamicInfo)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_NodeObserverPrx, 'nodeDown', 0, 0, 0, array(array($IcePHP__t_string)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_NodeObserverPrx, 'updateServer', 0, 0, 0, array(array($IcePHP__t_string), array($IceGrid__t_ServerDynamicInfo)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_NodeObserverPrx, 'updateAdapter', 0, 0, 0, array(array($IcePHP__t_string), array($IceGrid__t_AdapterDynamicInfo)), null, null, null);
}

namespace IceGrid
{
    global $IceGrid__t_ApplicationObserver;
    global $IceGrid__t_ApplicationObserverPrx;

    class ApplicationObserverPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::ApplicationObserver', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::ApplicationObserver', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::ApplicationObserver';
        }
    }
    $IceGrid__t_ApplicationObserver = IcePHP_defineClass('::IceGrid::ApplicationObserver', '\\IceGrid\\ApplicationObserver', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_ApplicationObserverPrx = IcePHP_defineProxy('::IceGrid::ApplicationObserver', $Ice__t_ObjectPrx, null);

    global $IcePHP__t_int;
    global $IceGrid__t_ApplicationInfoSeq;
    global $IceGrid__t_ApplicationInfo;
    global $IcePHP__t_string;
    global $IceGrid__t_ApplicationUpdateInfo;
    IcePHP_defineOperation($IceGrid__t_ApplicationObserverPrx, 'applicationInit', 0, 0, 0, array(array($IcePHP__t_int), array($IceGrid__t_ApplicationInfoSeq)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_ApplicationObserverPrx, 'applicationAdded', 0, 0, 0, array(array($IcePHP__t_int), array($IceGrid__t_ApplicationInfo)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_ApplicationObserverPrx, 'applicationRemoved', 0, 0, 0, array(array($IcePHP__t_int), array($IcePHP__t_string)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_ApplicationObserverPrx, 'applicationUpdated', 0, 0, 0, array(array($IcePHP__t_int), array($IceGrid__t_ApplicationUpdateInfo)), null, null, null);
}

namespace IceGrid
{
    global $IceGrid__t_AdapterObserver;
    global $IceGrid__t_AdapterObserverPrx;

    class AdapterObserverPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::AdapterObserver', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::AdapterObserver', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::AdapterObserver';
        }
    }
    $IceGrid__t_AdapterObserver = IcePHP_defineClass('::IceGrid::AdapterObserver', '\\IceGrid\\AdapterObserver', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_AdapterObserverPrx = IcePHP_defineProxy('::IceGrid::AdapterObserver', $Ice__t_ObjectPrx, null);

    global $IceGrid__t_AdapterInfoSeq;
    global $IceGrid__t_AdapterInfo;
    global $IcePHP__t_string;
    IcePHP_defineOperation($IceGrid__t_AdapterObserverPrx, 'adapterInit', 0, 0, 0, array(array($IceGrid__t_AdapterInfoSeq)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_AdapterObserverPrx, 'adapterAdded', 0, 0, 0, array(array($IceGrid__t_AdapterInfo)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_AdapterObserverPrx, 'adapterUpdated', 0, 0, 0, array(array($IceGrid__t_AdapterInfo)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_AdapterObserverPrx, 'adapterRemoved', 0, 0, 0, array(array($IcePHP__t_string)), null, null, null);
}

namespace IceGrid
{
    global $IceGrid__t_ObjectObserver;
    global $IceGrid__t_ObjectObserverPrx;

    class ObjectObserverPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::ObjectObserver', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::ObjectObserver', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::ObjectObserver';
        }
    }
    $IceGrid__t_ObjectObserver = IcePHP_defineClass('::IceGrid::ObjectObserver', '\\IceGrid\\ObjectObserver', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_ObjectObserverPrx = IcePHP_defineProxy('::IceGrid::ObjectObserver', $Ice__t_ObjectPrx, null);

    global $IceGrid__t_ObjectInfoSeq;
    global $IceGrid__t_ObjectInfo;
    global $Ice__t_Identity;
    IcePHP_defineOperation($IceGrid__t_ObjectObserverPrx, 'objectInit', 0, 0, 0, array(array($IceGrid__t_ObjectInfoSeq)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_ObjectObserverPrx, 'objectAdded', 0, 0, 0, array(array($IceGrid__t_ObjectInfo)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_ObjectObserverPrx, 'objectUpdated', 0, 0, 0, array(array($IceGrid__t_ObjectInfo)), null, null, null);
    IcePHP_defineOperation($IceGrid__t_ObjectObserverPrx, 'objectRemoved', 0, 0, 0, array(array($Ice__t_Identity)), null, null, null);
}

namespace IceGrid
{
    global $IceGrid__t_AdminSession;
    global $IceGrid__t_AdminSessionPrx;

    class AdminSessionPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::AdminSession', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::AdminSession', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::AdminSession';
        }
    }
    $IceGrid__t_AdminSession = IcePHP_defineClass('::IceGrid::AdminSession', '\\IceGrid\\AdminSession', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_AdminSessionPrx = IcePHP_defineProxy('::IceGrid::AdminSession', $Ice__t_ObjectPrx, array($Glacier2__t_SessionPrx));

    global $IceGrid__t_AdminPrx;
    global $Ice__t_ObjectPrx;
    global $IceGrid__t_RegistryObserverPrx;
    global $IceGrid__t_NodeObserverPrx;
    global $IceGrid__t_ApplicationObserverPrx;
    global $IceGrid__t_AdapterObserverPrx;
    global $IceGrid__t_ObjectObserverPrx;
    global $Ice__t_Identity;
    global $IcePHP__t_int;
    global $IcePHP__t_string;
    global $IceGrid__t_FileIteratorPrx;
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'keepAlive', 2, 2, 0, null, null, null, null);
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'getAdmin', 2, 1, 0, null, null, array($IceGrid__t_AdminPrx), null);
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'getAdminCallbackTemplate', 2, 2, 0, null, null, array($Ice__t_ObjectPrx), null);
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'setObservers', 2, 2, 0, array(array($IceGrid__t_RegistryObserverPrx), array($IceGrid__t_NodeObserverPrx), array($IceGrid__t_ApplicationObserverPrx), array($IceGrid__t_AdapterObserverPrx), array($IceGrid__t_ObjectObserverPrx)), null, null, array($IceGrid__t_ObserverAlreadyRegisteredException));
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'setObserversByIdentity', 2, 2, 0, array(array($Ice__t_Identity), array($Ice__t_Identity), array($Ice__t_Identity), array($Ice__t_Identity), array($Ice__t_Identity)), null, null, array($IceGrid__t_ObserverAlreadyRegisteredException));
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'startUpdate', 0, 0, 0, null, null, array($IcePHP__t_int), array($IceGrid__t_AccessDeniedException));
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'finishUpdate', 0, 0, 0, null, null, null, array($IceGrid__t_AccessDeniedException));
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'getReplicaName', 2, 2, 0, null, null, array($IcePHP__t_string), null);
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'openServerLog', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string), array($IcePHP__t_int)), null, array($IceGrid__t_FileIteratorPrx), array($IceGrid__t_FileNotAvailableException, $IceGrid__t_ServerNotExistException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'openServerStdErr', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_int)), null, array($IceGrid__t_FileIteratorPrx), array($IceGrid__t_FileNotAvailableException, $IceGrid__t_ServerNotExistException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'openServerStdOut', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_int)), null, array($IceGrid__t_FileIteratorPrx), array($IceGrid__t_FileNotAvailableException, $IceGrid__t_ServerNotExistException, $IceGrid__t_NodeUnreachableException, $IceGrid__t_DeploymentException));
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'openNodeStdErr', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_int)), null, array($IceGrid__t_FileIteratorPrx), array($IceGrid__t_FileNotAvailableException, $IceGrid__t_NodeNotExistException, $IceGrid__t_NodeUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'openNodeStdOut', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_int)), null, array($IceGrid__t_FileIteratorPrx), array($IceGrid__t_FileNotAvailableException, $IceGrid__t_NodeNotExistException, $IceGrid__t_NodeUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'openRegistryStdErr', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_int)), null, array($IceGrid__t_FileIteratorPrx), array($IceGrid__t_FileNotAvailableException, $IceGrid__t_RegistryNotExistException, $IceGrid__t_RegistryUnreachableException));
    IcePHP_defineOperation($IceGrid__t_AdminSessionPrx, 'openRegistryStdOut', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_int)), null, array($IceGrid__t_FileIteratorPrx), array($IceGrid__t_FileNotAvailableException, $IceGrid__t_RegistryNotExistException, $IceGrid__t_RegistryUnreachableException));
}
namespace
{new Ice\SliceChecksumInit(array(
    "::IceGrid::AdapterDynamicInfo" => "b371e9a58f115e6ebfbcda735fee57f7",
    "::IceGrid::AdapterDynamicInfoSeq" => "54465843167a2f93fa96d13b7f41ea32",
    "::IceGrid::AdapterInfo" => "a22de437e0d82d91cca7d476992b2a43",
    "::IceGrid::AdapterInfoSeq" => "9fdbbb3c2d938b4e5f3bf5a21f234147",
    "::IceGrid::AdapterObserver" => "7f4ed59e236da9d6c35ad7e6ad9cb0",
    "::IceGrid::Admin" => "35cb721cd375fb13818304b7c87217a",
    "::IceGrid::AdminSession" => "ca6f21e8ff4210158f382cdbc66c2566",
    "::IceGrid::ApplicationInfo" => "44ab5928481a1441216f93965f9e6c5",
    "::IceGrid::ApplicationInfoSeq" => "dc7429d6b923c3e66eea573eccc1598",
    "::IceGrid::ApplicationObserver" => "2862cdcba54714282f68b13a8fb4ae",
    "::IceGrid::ApplicationUpdateInfo" => "c21c8cfe85e332fd9ad194e611bc6b7f",
    "::IceGrid::FileIterator" => "54341a38932f89d199f28ffc4712c7",
    "::IceGrid::LoadInfo" => "c28c339f5af52a46ac64c33864ae6",
    "::IceGrid::NodeDynamicInfo" => "3ad52341f32973212d26a9a6dda08b",
    "::IceGrid::NodeDynamicInfoSeq" => "f61633c5e3992f718dba78b7f165c2",
    "::IceGrid::NodeInfo" => "f348b389deb653ac28b2b991e23d63b9",
    "::IceGrid::NodeObserver" => "e06c1ad6807d2876de9e818855a65738",
    "::IceGrid::ObjectInfo" => "6c8a382c348df5cbda50e58d87189e33",
    "::IceGrid::ObjectInfoSeq" => "1491c01cb93b575c602baed26ed0f989",
    "::IceGrid::ObjectObserver" => "5364683a872f127e46cc5e215d98c3c",
    "::IceGrid::RegistryInfo" => "60e64fc1e37ce59ecbeed4a0e276ba",
    "::IceGrid::RegistryInfoSeq" => "fabb868b9f2164f68bc9eb68240c8a6",
    "::IceGrid::RegistryObserver" => "fd83b1558e7c77f2d322b25449518",
    "::IceGrid::ServerDynamicInfo" => "fd4b9177ca54ae4688b51fa51d6870",
    "::IceGrid::ServerDynamicInfoSeq" => "e3fda58997d5cd946e78cae739174cb",
    "::IceGrid::ServerInfo" => "7f99dc872345b2c3c741c8b4c23440da",
    "::IceGrid::ServerState" => "21e8ecba86a4678f3b783de286583093",
    "::IceGrid::StringObjectProxyDict" => "978c325e58cebefb212e5ebde28acdc"));
}
?>
