<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `FileParser.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'IceGrid/Admin.php';
}

namespace IceGrid
{
    global $IceGrid__t_ParseException;
    class ParseException extends \Ice\UserException
    {
        public function __construct($reason='')
        {
            $this->reason = $reason;
        }

        public function ice_id()
        {
            return '::IceGrid::ParseException';
        }

        public function __toString()
        {
            global $IceGrid__t_ParseException;
            return IcePHP_stringifyException($this, $IceGrid__t_ParseException);
        }

        public $reason;
    }
    global $IcePHP__t_string;

    $IceGrid__t_ParseException = IcePHP_defineException('::IceGrid::ParseException', '\\IceGrid\\ParseException', false, null, array(
        array('reason', $IcePHP__t_string, false, 0)));
}

namespace IceGrid
{
    global $IceGrid__t_FileParser;
    global $IceGrid__t_FileParserPrx;

    class FileParserPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::FileParser', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::FileParser', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::FileParser';
        }
    }
    $IceGrid__t_FileParser = IcePHP_defineClass('::IceGrid::FileParser', '\\IceGrid\\FileParser', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_FileParserPrx = IcePHP_defineProxy('::IceGrid::FileParser', $Ice__t_ObjectPrx, null);

    global $IcePHP__t_string;
    global $IceGrid__t_AdminPrx;
    global $IceGrid__t_ApplicationDescriptor;
    IcePHP_defineOperation($IceGrid__t_FileParserPrx, 'parse', 2, 2, 0, array(array($IcePHP__t_string), array($IceGrid__t_AdminPrx)), null, array($IceGrid__t_ApplicationDescriptor), array($IceGrid__t_ParseException));
}
namespace
{new Ice\SliceChecksumInit(array(
    "::IceGrid::FileParser" => "b847ccf3e3db7cbba649ec7cc464faf",
    "::IceGrid::ParseException" => "dec9aacba8b3ba76afc5de1cc3489598"));
}
?>
