<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Registry.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'IceGrid/Exception.php';
    require_once 'IceGrid/Session.php';
    require_once 'IceGrid/Admin.php';
    require_once 'Ice/Locator.php';
}

namespace IceGrid
{
    global $IceGrid__t_LoadSample;
    class LoadSample
    {
        const LoadSample1 = 0;
        const LoadSample5 = 1;
        const LoadSample15 = 2;
    }

    $IceGrid__t_LoadSample = IcePHP_defineEnum('::IceGrid::LoadSample', array('LoadSample1', 0, 'LoadSample5', 1, 'LoadSample15', 2));
}

namespace IceGrid
{
    global $IceGrid__t_Query;
    global $IceGrid__t_QueryPrx;

    class QueryPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::Query', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::Query', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::Query';
        }
    }
    $IceGrid__t_Query = IcePHP_defineClass('::IceGrid::Query', '\\IceGrid\\Query', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_QueryPrx = IcePHP_defineProxy('::IceGrid::Query', $Ice__t_ObjectPrx, null);

    global $Ice__t_Identity;
    global $Ice__t_ObjectPrx;
    global $IcePHP__t_string;
    global $IceGrid__t_LoadSample;
    global $Ice__t_ObjectProxySeq;
    IcePHP_defineOperation($IceGrid__t_QueryPrx, 'findObjectById', 2, 1, 0, array(array($Ice__t_Identity)), null, array($Ice__t_ObjectPrx), null);
    IcePHP_defineOperation($IceGrid__t_QueryPrx, 'findObjectByType', 2, 1, 0, array(array($IcePHP__t_string)), null, array($Ice__t_ObjectPrx), null);
    IcePHP_defineOperation($IceGrid__t_QueryPrx, 'findObjectByTypeOnLeastLoadedNode', 2, 1, 0, array(array($IcePHP__t_string), array($IceGrid__t_LoadSample)), null, array($Ice__t_ObjectPrx), null);
    IcePHP_defineOperation($IceGrid__t_QueryPrx, 'findAllObjectsByType', 2, 1, 0, array(array($IcePHP__t_string)), null, array($Ice__t_ObjectProxySeq), null);
    IcePHP_defineOperation($IceGrid__t_QueryPrx, 'findAllReplicas', 2, 2, 0, array(array($Ice__t_ObjectPrx)), null, array($Ice__t_ObjectProxySeq), null);
}

namespace IceGrid
{
    global $IceGrid__t_Registry;
    global $IceGrid__t_RegistryPrx;

    class RegistryPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::Registry', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::Registry', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::Registry';
        }
    }
    $IceGrid__t_Registry = IcePHP_defineClass('::IceGrid::Registry', '\\IceGrid\\Registry', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_RegistryPrx = IcePHP_defineProxy('::IceGrid::Registry', $Ice__t_ObjectPrx, null);

    global $IcePHP__t_string;
    global $IceGrid__t_SessionPrx;
    global $IceGrid__t_AdminSessionPrx;
    global $IcePHP__t_int;
    IcePHP_defineOperation($IceGrid__t_RegistryPrx, 'createSession', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string)), null, array($IceGrid__t_SessionPrx), array($IceGrid__t_PermissionDeniedException));
    IcePHP_defineOperation($IceGrid__t_RegistryPrx, 'createAdminSession', 0, 0, 0, array(array($IcePHP__t_string), array($IcePHP__t_string)), null, array($IceGrid__t_AdminSessionPrx), array($IceGrid__t_PermissionDeniedException));
    IcePHP_defineOperation($IceGrid__t_RegistryPrx, 'createSessionFromSecureConnection', 0, 0, 0, null, null, array($IceGrid__t_SessionPrx), array($IceGrid__t_PermissionDeniedException));
    IcePHP_defineOperation($IceGrid__t_RegistryPrx, 'createAdminSessionFromSecureConnection', 0, 0, 0, null, null, array($IceGrid__t_AdminSessionPrx), array($IceGrid__t_PermissionDeniedException));
    IcePHP_defineOperation($IceGrid__t_RegistryPrx, 'getSessionTimeout', 2, 1, 0, null, null, array($IcePHP__t_int), null);
    IcePHP_defineOperation($IceGrid__t_RegistryPrx, 'getACMTimeout', 2, 1, 0, null, null, array($IcePHP__t_int), null);
}

namespace IceGrid
{
    global $IceGrid__t_Locator;
    global $IceGrid__t_LocatorPrx;

    class LocatorPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::Locator', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::Locator', $facet);
        }

        public static function ice_staticId()
        {
            return '::IceGrid::Locator';
        }
    }
    $IceGrid__t_Locator = IcePHP_defineClass('::IceGrid::Locator', '\\IceGrid\\Locator', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $IceGrid__t_LocatorPrx = IcePHP_defineProxy('::IceGrid::Locator', $Ice__t_ObjectPrx, array($Ice__t_LocatorPrx));

    global $IceGrid__t_RegistryPrx;
    global $IceGrid__t_QueryPrx;
    IcePHP_defineOperation($IceGrid__t_LocatorPrx, 'getLocalRegistry', 2, 2, 0, null, null, array($IceGrid__t_RegistryPrx), null);
    IcePHP_defineOperation($IceGrid__t_LocatorPrx, 'getLocalQuery', 2, 2, 0, null, null, array($IceGrid__t_QueryPrx), null);
}
namespace
{new Ice\SliceChecksumInit(array(
    "::IceGrid::LoadSample" => "ec48c06fa099138a5fbbce121a9a290",
    "::IceGrid::Locator" => "816e9d7a3cb39b8c80fe342e7f18ae",
    "::IceGrid::Query" => "39dbe5f62c19aa42c2e0fbaf220b4f1",
    "::IceGrid::Registry" => "8298cc0aba1a722d75eb79034fbb076"));
}
?>
