<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `BuiltinSequences.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_BoolSeq;

    if(!isset($Ice__t_BoolSeq))
    {
        global $IcePHP__t_bool;
        $Ice__t_BoolSeq = IcePHP_defineSequence('::Ice::BoolSeq', $IcePHP__t_bool);
    }
}

namespace Ice
{
    global $Ice__t_ByteSeq;

    if(!isset($Ice__t_ByteSeq))
    {
        global $IcePHP__t_byte;
        $Ice__t_ByteSeq = IcePHP_defineSequence('::Ice::ByteSeq', $IcePHP__t_byte);
    }
}

namespace Ice
{
    global $Ice__t_ShortSeq;

    if(!isset($Ice__t_ShortSeq))
    {
        global $IcePHP__t_short;
        $Ice__t_ShortSeq = IcePHP_defineSequence('::Ice::ShortSeq', $IcePHP__t_short);
    }
}

namespace Ice
{
    global $Ice__t_IntSeq;

    if(!isset($Ice__t_IntSeq))
    {
        global $IcePHP__t_int;
        $Ice__t_IntSeq = IcePHP_defineSequence('::Ice::IntSeq', $IcePHP__t_int);
    }
}

namespace Ice
{
    global $Ice__t_LongSeq;

    if(!isset($Ice__t_LongSeq))
    {
        global $IcePHP__t_long;
        $Ice__t_LongSeq = IcePHP_defineSequence('::Ice::LongSeq', $IcePHP__t_long);
    }
}

namespace Ice
{
    global $Ice__t_FloatSeq;

    if(!isset($Ice__t_FloatSeq))
    {
        global $IcePHP__t_float;
        $Ice__t_FloatSeq = IcePHP_defineSequence('::Ice::FloatSeq', $IcePHP__t_float);
    }
}

namespace Ice
{
    global $Ice__t_DoubleSeq;

    if(!isset($Ice__t_DoubleSeq))
    {
        global $IcePHP__t_double;
        $Ice__t_DoubleSeq = IcePHP_defineSequence('::Ice::DoubleSeq', $IcePHP__t_double);
    }
}

namespace Ice
{
    global $Ice__t_StringSeq;

    if(!isset($Ice__t_StringSeq))
    {
        global $IcePHP__t_string;
        $Ice__t_StringSeq = IcePHP_defineSequence('::Ice::StringSeq', $IcePHP__t_string);
    }
}

namespace Ice
{
    global $Ice__t_ObjectSeq;

    if(!isset($Ice__t_ObjectSeq))
    {
        global $Ice__t_Value;
        $Ice__t_ObjectSeq = IcePHP_defineSequence('::Ice::ObjectSeq', $Ice__t_Value);
    }
}

namespace Ice
{
    global $Ice__t_ObjectProxySeq;

    if(!isset($Ice__t_ObjectProxySeq))
    {
        global $Ice__t_ObjectPrx;
        $Ice__t_ObjectProxySeq = IcePHP_defineSequence('::Ice::ObjectProxySeq', $Ice__t_ObjectPrx);
    }
}
namespace
{new Ice\SliceChecksumInit(array(
    "::Ice::BoolSeq" => "321b1d4186eaf796937e82eed711fe7f",
    "::Ice::ByteSeq" => "eae189e6d7b57b6f9628e78293d6d7",
    "::Ice::DoubleSeq" => "7fb8b78b3ab4b2e358d27dc4d6f1e330",
    "::Ice::FloatSeq" => "eb848491fad1518427fd58a7330958e",
    "::Ice::IntSeq" => "826eab2e95b89b0476198b6a36991dc",
    "::Ice::LongSeq" => "325a51044cdee10b14ecc3c1672a86",
    "::Ice::ObjectProxySeq" => "45ccc241c2bbfebfbd031e733a5832",
    "::Ice::ObjectSeq" => "a1e80bc6b87e9687455a4faa4c2f295",
    "::Ice::ShortSeq" => "32aadcc785b88fc7198ae3d262ff3acd",
    "::Ice::StringSeq" => "7986f19514e3b04fbe4af53c7446e563"));
}
?>
