<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Communicator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/LoggerF.php';
    require_once 'Ice/InstrumentationF.php';
    require_once 'Ice/ObjectAdapterF.php';
    require_once 'Ice/ObjectFactory.php';
    require_once 'Ice/ValueFactory.php';
    require_once 'Ice/Router.php';
    require_once 'Ice/Locator.php';
    require_once 'Ice/PluginF.php';
    require_once 'Ice/ImplicitContextF.php';
    require_once 'Ice/Current.php';
    require_once 'Ice/Properties.php';
    require_once 'Ice/FacetMap.php';
    require_once 'Ice/Connection.php';
}

namespace Ice
{
    global $Ice__t_ToStringMode;
    class ToStringMode
    {
        const Unicode = 0;
        const ASCII = 1;
        const Compat = 2;
    }

    $Ice__t_ToStringMode = IcePHP_defineEnum('::Ice::ToStringMode', array('Unicode', 0, 'ASCII', 1, 'Compat', 2));
}
?>
