<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `EndpointTypes.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_EndpointSelectionType;
    class EndpointSelectionType
    {
        const Random = 0;
        const Ordered = 1;
    }

    $Ice__t_EndpointSelectionType = IcePHP_defineEnum('::Ice::EndpointSelectionType', array('Random', 0, 'Ordered', 1));
}
?>
