<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Endpoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/Version.php';
    require_once 'Ice/BuiltinSequences.php';
    require_once 'Ice/EndpointF.php';
}

namespace Ice
{
    if(!defined('\\Ice\\TCPEndpointType'))
    {
        define(__NAMESPACE__ . '\\TCPEndpointType', 1);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\SSLEndpointType'))
    {
        define(__NAMESPACE__ . '\\SSLEndpointType', 2);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\UDPEndpointType'))
    {
        define(__NAMESPACE__ . '\\UDPEndpointType', 3);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\WSEndpointType'))
    {
        define(__NAMESPACE__ . '\\WSEndpointType', 4);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\WSSEndpointType'))
    {
        define(__NAMESPACE__ . '\\WSSEndpointType', 5);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\BTEndpointType'))
    {
        define(__NAMESPACE__ . '\\BTEndpointType', 6);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\BTSEndpointType'))
    {
        define(__NAMESPACE__ . '\\BTSEndpointType', 7);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\iAPEndpointType'))
    {
        define(__NAMESPACE__ . '\\iAPEndpointType', 8);
    }
}

namespace Ice
{
    if(!defined('\\Ice\\iAPSEndpointType'))
    {
        define(__NAMESPACE__ . '\\iAPSEndpointType', 9);
    }
}
namespace
{new Ice\SliceChecksumInit(array(
    "::Ice::BTEndpointType" => "bf2c14e5c7ae9b47c4306e35b744efbd",
    "::Ice::BTSEndpointType" => "91c6c150f7d5678cdc541a82852a8f1",
    "::Ice::SSLEndpointType" => "846ad753a0862cc0c55a4ff278181b15",
    "::Ice::TCPEndpointType" => "19d61f4b55a285927bb1648f7a943c29",
    "::Ice::UDPEndpointType" => "20cb65b86f212e8c67dfa0314854eaf1",
    "::Ice::WSEndpointType" => "9d96d5f9ecade1e2a84f6187d644b92d",
    "::Ice::WSSEndpointType" => "e4c22485e7afe76aadc2921852b6182b",
    "::Ice::iAPEndpointType" => "c170d414154fdef5ae94dedb8ec07bf",
    "::Ice::iAPSEndpointType" => "87796981d5b8ab436f975e663c75d4a"));
}
?>
