<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `LocatorF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_Locator;
    global $Ice__t_LocatorPrx;
    if(!isset($Ice__t_Locator))
    {
        $Ice__t_Locator = IcePHP_declareClass('::Ice::Locator');
        $Ice__t_LocatorPrx = IcePHP_declareProxy('::Ice::Locator');
    }
}

namespace Ice
{
    global $Ice__t_LocatorRegistry;
    global $Ice__t_LocatorRegistryPrx;
    if(!isset($Ice__t_LocatorRegistry))
    {
        $Ice__t_LocatorRegistry = IcePHP_declareClass('::Ice::LocatorRegistry');
        $Ice__t_LocatorRegistryPrx = IcePHP_declareProxy('::Ice::LocatorRegistry');
    }
}
?>
