<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `ProcessF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_Process;
    global $Ice__t_ProcessPrx;
    if(!isset($Ice__t_Process))
    {
        $Ice__t_Process = IcePHP_declareClass('::Ice::Process');
        $Ice__t_ProcessPrx = IcePHP_declareProxy('::Ice::Process');
    }
}
?>
