<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `PropertiesAdmin.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/BuiltinSequences.php';
}

namespace Ice
{
    global $Ice__t_PropertyDict;

    if(!isset($Ice__t_PropertyDict))
    {
        global $IcePHP__t_string;
        global $IcePHP__t_string;
        $Ice__t_PropertyDict = IcePHP_defineDictionary('::Ice::PropertyDict', $IcePHP__t_string, $IcePHP__t_string);
    }
}

namespace Ice
{
    global $Ice__t_PropertiesAdmin;
    global $Ice__t_PropertiesAdminPrx;

    class PropertiesAdminPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Ice::PropertiesAdmin', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Ice::PropertiesAdmin', $facet);
        }

        public static function ice_staticId()
        {
            return '::Ice::PropertiesAdmin';
        }
    }
    $Ice__t_PropertiesAdmin = IcePHP_defineClass('::Ice::PropertiesAdmin', '\\Ice\\PropertiesAdmin', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $Ice__t_PropertiesAdminPrx = IcePHP_defineProxy('::Ice::PropertiesAdmin', $Ice__t_ObjectPrx, null);

    global $IcePHP__t_string;
    global $Ice__t_PropertyDict;
    IcePHP_defineOperation($Ice__t_PropertiesAdminPrx, 'getProperty', 0, 0, 0, array(array($IcePHP__t_string)), null, array($IcePHP__t_string), null);
    IcePHP_defineOperation($Ice__t_PropertiesAdminPrx, 'getPropertiesForPrefix', 0, 0, 0, array(array($IcePHP__t_string)), null, array($Ice__t_PropertyDict), null);
    IcePHP_defineOperation($Ice__t_PropertiesAdminPrx, 'setProperties', 0, 0, 0, array(array($Ice__t_PropertyDict)), null, null, null);
}
namespace
{new Ice\SliceChecksumInit(array(
    "::Ice::PropertiesAdmin" => "2fdc55e4b6d63dcc2fa612b79b57c6e",
    "::Ice::PropertyDict" => "28c9538d4ffc29a24c3cf15fff4f329"));
}
?>
