<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `RemoteLogger.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/BuiltinSequences.php';
}

namespace Ice
{
    global $Ice__t_LogMessageType;
    class LogMessageType
    {
        const PrintMessage = 0;
        const TraceMessage = 1;
        const WarningMessage = 2;
        const ErrorMessage = 3;
    }

    $Ice__t_LogMessageType = IcePHP_defineEnum('::Ice::LogMessageType', array('PrintMessage', 0, 'TraceMessage', 1, 'WarningMessage', 2, 'ErrorMessage', 3));
}

namespace Ice
{
    global $Ice__t_LogMessageTypeSeq;

    if(!isset($Ice__t_LogMessageTypeSeq))
    {
        global $Ice__t_LogMessageType;
        $Ice__t_LogMessageTypeSeq = IcePHP_defineSequence('::Ice::LogMessageTypeSeq', $Ice__t_LogMessageType);
    }
}

namespace Ice
{
    global $Ice__t_LogMessage;
    class LogMessage
    {
        public function __construct($type=\Ice\LogMessageType::PrintMessage, $timestamp=0, $traceCategory='', $message='')
        {
            $this->type = $type;
            $this->timestamp = $timestamp;
            $this->traceCategory = $traceCategory;
            $this->message = $message;
        }

        public function __toString()
        {
            global $Ice__t_LogMessage;
            return IcePHP_stringify($this, $Ice__t_LogMessage);
        }

        public $type;
        public $timestamp;
        public $traceCategory;
        public $message;
    }

    global $Ice__t_LogMessageType;
    global $IcePHP__t_long;
    global $IcePHP__t_string;
    $Ice__t_LogMessage = IcePHP_defineStruct('::Ice::LogMessage', '\\Ice\\LogMessage', array(
        array('type', $Ice__t_LogMessageType),
        array('timestamp', $IcePHP__t_long),
        array('traceCategory', $IcePHP__t_string),
        array('message', $IcePHP__t_string)));
}

namespace Ice
{
    global $Ice__t_LogMessageSeq;

    if(!isset($Ice__t_LogMessageSeq))
    {
        global $Ice__t_LogMessage;
        $Ice__t_LogMessageSeq = IcePHP_defineSequence('::Ice::LogMessageSeq', $Ice__t_LogMessage);
    }
}

namespace Ice
{
    global $Ice__t_RemoteLogger;
    global $Ice__t_RemoteLoggerPrx;

    class RemoteLoggerPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Ice::RemoteLogger', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Ice::RemoteLogger', $facet);
        }

        public static function ice_staticId()
        {
            return '::Ice::RemoteLogger';
        }
    }
    $Ice__t_RemoteLogger = IcePHP_defineClass('::Ice::RemoteLogger', '\\Ice\\RemoteLogger', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $Ice__t_RemoteLoggerPrx = IcePHP_defineProxy('::Ice::RemoteLogger', $Ice__t_ObjectPrx, null);

    global $IcePHP__t_string;
    global $Ice__t_LogMessageSeq;
    global $Ice__t_LogMessage;
    IcePHP_defineOperation($Ice__t_RemoteLoggerPrx, 'init', 0, 0, 0, array(array($IcePHP__t_string), array($Ice__t_LogMessageSeq)), null, null, null);
    IcePHP_defineOperation($Ice__t_RemoteLoggerPrx, 'log', 0, 0, 0, array(array($Ice__t_LogMessage)), null, null, null);
}

namespace Ice
{
    global $Ice__t_RemoteLoggerAlreadyAttachedException;
    class RemoteLoggerAlreadyAttachedException extends \Ice\UserException
    {
        public function __construct()
        {
        }

        public function ice_id()
        {
            return '::Ice::RemoteLoggerAlreadyAttachedException';
        }

        public function __toString()
        {
            global $Ice__t_RemoteLoggerAlreadyAttachedException;
            return IcePHP_stringifyException($this, $Ice__t_RemoteLoggerAlreadyAttachedException);
        }
    }

    $Ice__t_RemoteLoggerAlreadyAttachedException = IcePHP_defineException('::Ice::RemoteLoggerAlreadyAttachedException', '\\Ice\\RemoteLoggerAlreadyAttachedException', false, null, null);
}

namespace Ice
{
    global $Ice__t_LoggerAdmin;
    global $Ice__t_LoggerAdminPrx;

    class LoggerAdminPrxHelper
    {
        public static function checkedCast($proxy, $facetOrContext=null, $context=null)
        {
            return $proxy->ice_checkedCast('::Ice::LoggerAdmin', $facetOrContext, $context);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Ice::LoggerAdmin', $facet);
        }

        public static function ice_staticId()
        {
            return '::Ice::LoggerAdmin';
        }
    }
    $Ice__t_LoggerAdmin = IcePHP_defineClass('::Ice::LoggerAdmin', '\\Ice\\LoggerAdmin', -1, false, true, null, null);

    global $Ice__t_ObjectPrx;
    $Ice__t_LoggerAdminPrx = IcePHP_defineProxy('::Ice::LoggerAdmin', $Ice__t_ObjectPrx, null);

    global $Ice__t_RemoteLoggerPrx;
    global $Ice__t_LogMessageTypeSeq;
    global $Ice__t_StringSeq;
    global $IcePHP__t_int;
    global $IcePHP__t_bool;
    global $IcePHP__t_string;
    global $Ice__t_LogMessageSeq;
    IcePHP_defineOperation($Ice__t_LoggerAdminPrx, 'attachRemoteLogger', 0, 0, 0, array(array($Ice__t_RemoteLoggerPrx), array($Ice__t_LogMessageTypeSeq), array($Ice__t_StringSeq), array($IcePHP__t_int)), null, null, array($Ice__t_RemoteLoggerAlreadyAttachedException));
    IcePHP_defineOperation($Ice__t_LoggerAdminPrx, 'detachRemoteLogger', 0, 0, 0, array(array($Ice__t_RemoteLoggerPrx)), null, array($IcePHP__t_bool), null);
    IcePHP_defineOperation($Ice__t_LoggerAdminPrx, 'getLog', 0, 0, 0, array(array($Ice__t_LogMessageTypeSeq), array($Ice__t_StringSeq), array($IcePHP__t_int)), array(array($IcePHP__t_string)), array($Ice__t_LogMessageSeq), null);
}
namespace
{new Ice\SliceChecksumInit(array(
    "::Ice::LogMessage" => "b3e905f1b794f505c1f817935be760",
    "::Ice::LogMessageSeq" => "26c45475ae04c87944249ec14ebe9c",
    "::Ice::LogMessageType" => "938bafca5970dc253c1e82a4c8ee234b",
    "::Ice::LogMessageTypeSeq" => "cb11159511adf1a74eb2901796137d7",
    "::Ice::LoggerAdmin" => "cba78eeef4c84241e3677c18bbccfb0",
    "::Ice::RemoteLogger" => "8c4657be5994cd2ccf54ae795b97273",
    "::Ice::RemoteLoggerAlreadyAttachedException" => "c0cffbaeb5ca2d0e1d4a0f328a701b"));
}
?>
