<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `RouterF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_Router;
    global $Ice__t_RouterPrx;
    if(!isset($Ice__t_Router))
    {
        $Ice__t_Router = IcePHP_declareClass('::Ice::Router');
        $Ice__t_RouterPrx = IcePHP_declareProxy('::Ice::Router');
    }
}
?>
