<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `ServantLocator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/ObjectAdapterF.php';
    require_once 'Ice/Current.php';
}

namespace Ice
{
    global $Ice__t_ServantLocator;
    interface ServantLocator
    {
        public function locate($curr, $cookie);
        public function finished($curr, $servant, $cookie);
        public function deactivate($category);
    }
    $Ice__t_ServantLocator = IcePHP_defineClass('::Ice::ServantLocator', '\\Ice\\ServantLocator', -1, false, true, null, null);
}
?>
