<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `SliceChecksumDict.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_SliceChecksumDict;

    if(!isset($Ice__t_SliceChecksumDict))
    {
        global $IcePHP__t_string;
        global $IcePHP__t_string;
        $Ice__t_SliceChecksumDict = IcePHP_defineDictionary('::Ice::SliceChecksumDict', $IcePHP__t_string, $IcePHP__t_string);
    }
}
namespace
{new Ice\SliceChecksumInit(array(
    "::Ice::SliceChecksumDict" => "d733c49f2c6d79a346ca7d695f0519"));
}
?>
