<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Version.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_ProtocolVersion;
    class ProtocolVersion
    {
        public function __construct($major=0, $minor=0)
        {
            $this->major = $major;
            $this->minor = $minor;
        }

        public function __toString()
        {
            global $Ice__t_ProtocolVersion;
            return IcePHP_stringify($this, $Ice__t_ProtocolVersion);
        }

        public $major;
        public $minor;
    }

    global $IcePHP__t_byte;
    $Ice__t_ProtocolVersion = IcePHP_defineStruct('::Ice::ProtocolVersion', '\\Ice\\ProtocolVersion', array(
        array('major', $IcePHP__t_byte),
        array('minor', $IcePHP__t_byte)));
}

namespace Ice
{
    global $Ice__t_EncodingVersion;
    class EncodingVersion
    {
        public function __construct($major=0, $minor=0)
        {
            $this->major = $major;
            $this->minor = $minor;
        }

        public function __toString()
        {
            global $Ice__t_EncodingVersion;
            return IcePHP_stringify($this, $Ice__t_EncodingVersion);
        }

        public $major;
        public $minor;
    }

    global $IcePHP__t_byte;
    $Ice__t_EncodingVersion = IcePHP_defineStruct('::Ice::EncodingVersion', '\\Ice\\EncodingVersion', array(
        array('major', $IcePHP__t_byte),
        array('minor', $IcePHP__t_byte)));
}
namespace
{new Ice\SliceChecksumInit(array(
    "::Ice::EncodingVersion" => "68abf5e483fdca188a95d11537ee5c8",
    "::Ice::ProtocolVersion" => "59bbb2793242c1ad2cb72e920ff65b0"));
}
?>
