<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `FileInfo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/BuiltinSequences.php';
}

namespace IcePatch2
{
    global $IcePatch2__t_FileInfo;
    class FileInfo
    {
        public function __construct($path='', $checksum=null, $size=0, $executable=false)
        {
            $this->path = $path;
            $this->checksum = $checksum;
            $this->size = $size;
            $this->executable = $executable;
        }

        public function __toString()
        {
            global $IcePatch2__t_FileInfo;
            return IcePHP_stringify($this, $IcePatch2__t_FileInfo);
        }

        public $path;
        public $checksum;
        public $size;
        public $executable;
    }

    global $IcePHP__t_string;
    global $Ice__t_ByteSeq;
    global $IcePHP__t_int;
    global $IcePHP__t_bool;
    $IcePatch2__t_FileInfo = IcePHP_defineStruct('::IcePatch2::FileInfo', '\\IcePatch2\\FileInfo', array(
        array('path', $IcePHP__t_string),
        array('checksum', $Ice__t_ByteSeq),
        array('size', $IcePHP__t_int),
        array('executable', $IcePHP__t_bool)));
}

namespace IcePatch2
{
    global $IcePatch2__t_FileInfoSeq;

    if(!isset($IcePatch2__t_FileInfoSeq))
    {
        global $IcePatch2__t_FileInfo;
        $IcePatch2__t_FileInfoSeq = IcePHP_defineSequence('::IcePatch2::FileInfoSeq', $IcePatch2__t_FileInfo);
    }
}

namespace IcePatch2
{
    global $IcePatch2__t_LargeFileInfo;
    class LargeFileInfo
    {
        public function __construct($path='', $checksum=null, $size=0, $executable=false)
        {
            $this->path = $path;
            $this->checksum = $checksum;
            $this->size = $size;
            $this->executable = $executable;
        }

        public function __toString()
        {
            global $IcePatch2__t_LargeFileInfo;
            return IcePHP_stringify($this, $IcePatch2__t_LargeFileInfo);
        }

        public $path;
        public $checksum;
        public $size;
        public $executable;
    }

    global $IcePHP__t_string;
    global $Ice__t_ByteSeq;
    global $IcePHP__t_long;
    global $IcePHP__t_bool;
    $IcePatch2__t_LargeFileInfo = IcePHP_defineStruct('::IcePatch2::LargeFileInfo', '\\IcePatch2\\LargeFileInfo', array(
        array('path', $IcePHP__t_string),
        array('checksum', $Ice__t_ByteSeq),
        array('size', $IcePHP__t_long),
        array('executable', $IcePHP__t_bool)));
}

namespace IcePatch2
{
    global $IcePatch2__t_LargeFileInfoSeq;

    if(!isset($IcePatch2__t_LargeFileInfoSeq))
    {
        global $IcePatch2__t_LargeFileInfo;
        $IcePatch2__t_LargeFileInfoSeq = IcePHP_defineSequence('::IcePatch2::LargeFileInfoSeq', $IcePatch2__t_LargeFileInfo);
    }
}
namespace
{new Ice\SliceChecksumInit(array(
    "::IcePatch2::FileInfo" => "4c71622889c19c7d3b5ef8210245",
    "::IcePatch2::FileInfoSeq" => "892945a7a7bfb532f6148c4be9889bd",
    "::IcePatch2::LargeFileInfo" => "c711b1cd93bfe8cab428a3201e0f291",
    "::IcePatch2::LargeFileInfoSeq" => "96e1aec0272b42f09289701462bb5921"));
}
?>
