<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Metrics.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace
{
    require_once 'Ice/Metrics.php';
}

namespace IceMX
{
    global $IceMX__t_TopicMetrics;
    class TopicMetrics extends \IceMX\Metrics
    {
        public function __construct($id='', $total=0, $current=0, $totalLifetime=0, $failures=0, $published=0, $forwarded=0)
        {
            parent::__construct($id, $total, $current, $totalLifetime, $failures);
            $this->published = $published;
            $this->forwarded = $forwarded;
        }

        public function ice_id()
        {
            return '::IceMX::TopicMetrics';
        }

        public static function ice_staticId()
        {
            return '::IceMX::TopicMetrics';
        }

        public function __toString()
        {
            global $IceMX__t_TopicMetrics;
            return IcePHP_stringify($this, $IceMX__t_TopicMetrics);
        }

        public $published;
        public $forwarded;
    }

    global $IceMX__t_Metrics;
    global $IcePHP__t_long;
    $IceMX__t_TopicMetrics = IcePHP_defineClass('::IceMX::TopicMetrics', '\\IceMX\\TopicMetrics', -1, false, false, $IceMX__t_Metrics, array(
        array('published', $IcePHP__t_long, false, 0),
        array('forwarded', $IcePHP__t_long, false, 0)));
}

namespace IceMX
{
    global $IceMX__t_SubscriberMetrics;
    class SubscriberMetrics extends \IceMX\Metrics
    {
        public function __construct($id='', $total=0, $current=0, $totalLifetime=0, $failures=0, $queued=0, $outstanding=0, $delivered=0)
        {
            parent::__construct($id, $total, $current, $totalLifetime, $failures);
            $this->queued = $queued;
            $this->outstanding = $outstanding;
            $this->delivered = $delivered;
        }

        public function ice_id()
        {
            return '::IceMX::SubscriberMetrics';
        }

        public static function ice_staticId()
        {
            return '::IceMX::SubscriberMetrics';
        }

        public function __toString()
        {
            global $IceMX__t_SubscriberMetrics;
            return IcePHP_stringify($this, $IceMX__t_SubscriberMetrics);
        }

        public $queued;
        public $outstanding;
        public $delivered;
    }

    global $IceMX__t_Metrics;
    global $IcePHP__t_int;
    global $IcePHP__t_long;
    $IceMX__t_SubscriberMetrics = IcePHP_defineClass('::IceMX::SubscriberMetrics', '\\IceMX\\SubscriberMetrics', -1, false, false, $IceMX__t_Metrics, array(
        array('queued', $IcePHP__t_int, false, 0),
        array('outstanding', $IcePHP__t_int, false, 0),
        array('delivered', $IcePHP__t_long, false, 0)));
}
namespace
{new Ice\SliceChecksumInit(array(
    "::IceMX::SubscriberMetrics" => "ab5eddbb2d0449f94b4808b6cf92552",
    "::IceMX::TopicMetrics" => "afc516f773371c41f4f612d9e9629c"));
}
?>
